### ISSUE TITLE
Tracking issue for RFC 50: `Print` statement and string formatting

### ISSUE THREAD

**Issue by wanda-phi** [amaranth-lang/amaranth#1186]
* RFC PR: amaranth-lang/rfcs#50
* Implementation PR: #1190
* Yosys feature implementation PR: https://github.com/YosysHQ/yosys/pull/4301
* Yosys version bump PR: #1309 
* RTLIL backend extension PR: #1280

**Comment by wanda-phi** [comment]
Most of this is done in #1190; However, yosys doesn't yet support some `Format` features. The plan is:

- [ ] add missing features to yosys, extending its format language
- [ ] wait for yosys release
- [ ] bump yosys version requirement
- [ ] change RTLIL backend to actually emit the newly added format specifiers

The missing features are:

- [ ] `X` type specifier (uppercase hex), which will probably be called `H` in yosys
- [ ] `=` alignment mode
- [ ] arbitrary fill byte (yosys only supports ` ` and `0`)
- [ ] `0`, `#`, and `_` options
- [ ] ` ` as sign
- [ ] (usefulness unclear) a mode to print a value as single Unicode character (currently we can only support ASCII via `c`)
