### ISSUE TITLE
Tracking issue for RFC 65: Special formatting for structures and enums

### ISSUE THREAD

**Issue by wanda-phi** [amaranth-lang/amaranth#1293]
- RFC PR: amaranth-lang/rfcs#65
- Implementation PRs:
  - [x] add `Format.*` classes: #1316 
  - [x] use `Format.*` in `lib.enum`: #1320 
  - [x] use `Format.*` in `lib.data`: #1321
  - [x] use `Format.*` for RTLIL output: #1323
  - [x] use `Format.*` for VCD output: #1326
