### ISSUE TITLE
ASIC support tracking issue

### ISSUE THREAD

**Issue by nmigen-issue-migration** [amaranth-lang/amaranth#185]
<a href="https://github.com/whitequark"><img src="https://avatars1.githubusercontent.com/u/54771?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [whitequark](https://github.com/whitequark)**
_Thursday Aug 22, 2019 at 21:49 GMT_
_Originally opened as https://github.com/m-labs/nmigen/issues/184_

----

A number of people have expressed a desire to use nMigen for ASIC design. This issue tracks missing aspects of that workflow.

 - [x] On FPGAs, asynchronous resets inhibit inference of BRAMs, DSPs, etc. On ASICs, asynchronous resets are required to make sure the chip is reset properly even with no clock.
 - [ ] On FPGAs, resets are generally positive polarity, and using the wrong polarity can have severe consequences for timing. On ASICs, resets are generally negative polarity, such that the chip is held in reset during power rail ramp-up.
 - [ ] On ASICs and in some cases on FPGAs, memories may not be initialized.
 - [ ] On ASICs, `reset_less` signals are not initialized at power-on.

(There are likely more.)

**Comment by whitequark** [comment]
@Fatsie you're interested in active low resets for ASIC work, right? I was wondering if you have any opinion on handling `ResetSignal` in that case; unlike `ClockSignal`, a lot of generic code depends on `ResetSignal` polarity being logic level (i.e. active high), so if we add clock domains with negative polarity resets that have inverted levels of `ResetSignal`, all such logic will break. There are a few solutions I can think of, but none are ideal.

**Comment by Fatsie** [comment]
@whitequark I don't think it is a problem to have nmigen only have active high reset support in it's clock domain.
For ASICs you typically want the external reset pin active low so you can keep the reset low during power ramp up by a simple RC circuit. But you can handle that by PinsN definition for the platform. If the standard cell library would have flip-flops with active low set and reset signals yosys should optimize away the two inverters in the logic path of the set/reset signal.

**Comment by hofstee** [comment]
I've seen lots of inverters get added to a design since tools will often synthesize things to use active-low resets (sometimes due to what's available in technology libraries). That ends up leading to a bunch of extra inverters in the design, especially at black-box boundaries where you've synthesized something to be used as a hard macro elsewhere (back to back inverters in timing reports confused the heck out of me for a while).

I can't say to what degree it actually affected the quality of the design, I don't remember the numbers at the moment.

**Comment by whitequark** [comment]
One possible solution here would be to add a late-bound `ResetActive()` AST node (so that, if you are branching on a reset in a generic module, you'd need to use `m.If(ResetActive())` rather than `m.If(ResetSignal())`), and then emit a diagnostic on use of `m.If(ResetSignal())`.

**Comment by Fatsie** [comment]
> I've seen lots of inverters get added to a design since tools will often synthesize things to use active-low resets (sometimes due to what's available in technology libraries). That ends up leading to a bunch of extra inverters in the design, especially at black-box boundaries where you've synthesized something to be used as a hard macro elsewhere (back to back inverters in timing reports confused the heck out of me for a while).

For ASIC one typically does tech mapping on the full flattened design, this allows yosys optimization pass to removed all double inverters.

**Comment by hofstee** [comment]
> For ASIC one typically does tech mapping on the full flattened design, this allows yosys optimization pass to remove all double inverters.

We were using Design Compiler and Innovus, not yosys (same problem, different source language than nmigen). The issue in our case stems from the fact that we have a repeated architecture with the same elements stamped out multiple times. To speed up synthesis, we synthesize each of the repeated elements and then stamp them out as hard macros at the top level. The double-inverters are seen at the boundaries of the hard macros and won't be optimized out.
